version: "3.8"

services:
  hhvm:
    build:
      dockerfile: ./hack-examples/Dockerfile
    image: hhvm/hhvm:latest
    ports:
      - "80:80"
    volumes:
      - ./:/root/projects
    command: /usr/bin/hhvm -m server -p 80 -d /root/projects -vServer.AllowRunAsRoot=1 -d hhvm.log.level=Verbose
    container_name: hhvm
